#!/bin/bash

# Script para facilitar a importação dos workflows corrigidos
# Data: 2026-01-12

echo "═══════════════════════════════════════════════════════════════"
echo "   📦 WORKFLOWS CORRIGIDOS PRONTOS PARA IMPORTAÇÃO"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ WORKFLOWS DISPONÍVEIS:"
echo ""
echo "1. Workflow 01 - WhatsApp Handler (Corrigido - Sem updated_at):"
echo "   📁 01_main_whatsapp_handler_V2.5_DEDUP_FIXED_NO_UPDATED_AT.json"
echo ""
echo "2. Workflow 02 - AI Agent V17 (Corrigido - Query String):"
echo "   📁 02_ai_agent_conversation_V17_QUERY_FIXED.json"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 INSTRUÇÕES DE IMPORTAÇÃO:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Acesse o n8n: http://localhost:5678"
echo ""
echo "2. Para o WORKFLOW 01:"
echo "   a) Vá em Workflows → Import from File"
echo "   b) Selecione: 01_main_whatsapp_handler_V2.5_DEDUP_FIXED_NO_UPDATED_AT.json"
echo "   c) DESATIVE o workflow '01 - WhatsApp Handle_V25' antigo"
echo "   d) ATIVE o novo workflow importado"
echo ""
echo "3. Para o WORKFLOW 02 (V17):"
echo "   a) Vá em Workflows → Import from File"
echo "   b) Selecione: 02_ai_agent_conversation_V17_QUERY_FIXED.json"
echo "   c) DESATIVE o workflow 'AI Agent Conversation - V17' antigo"
echo "   d) ATIVE o novo workflow importado"
echo ""
echo "4. Teste enviando uma mensagem no WhatsApp"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔍 VERIFICAÇÃO PÓS-IMPORTAÇÃO:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Execute o comando abaixo para verificar os logs:"
echo "docker logs -f e2bot-n8n-dev 2>&1 | grep -E '(error|Error|ERROR)'"
echo ""
echo "Se não aparecer nenhum erro novo, a correção foi bem-sucedida!"
echo ""
echo "═══════════════════════════════════════════════════════════════"

# Copiar caminhos completos para facilitar
echo ""
echo "📂 CAMINHOS COMPLETOS (copie e cole no n8n):"
echo ""
echo "/home/bruno/Desktop/Programas/E2_Solucoes/e2-solucoes-bot/n8n/workflows/01_main_whatsapp_handler_V2.5_DEDUP_FIXED_NO_UPDATED_AT.json"
echo ""
echo "/home/bruno/Desktop/Programas/E2_Solucoes/e2-solucoes-bot/n8n/workflows/02_ai_agent_conversation_V17_QUERY_FIXED.json"
echo ""